version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  static_volume:
